<template>
  <div class="p-4">
    <h1>優惠管理</h1>
        <table class="table">
          <thead>
            <tr>
              <td>測試</td>
              <td>測試</td>
              <td>測試</td>
              <td>測試</td>
              <td>測試</td>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
         <h1>優惠管理</h1>
         <h1>優惠管理</h1>
         <h1>優惠管理</h1>
         <h1>優惠管理</h1>
         <h1>優惠管理</h1>
         <h1>優惠管理</h1>
         <h1>優惠管理</h1>
         <h1>優惠管理</h1>
         <h1>優惠管理</h1>
         <h1>優惠管理</h1>
         <h1>優惠管理</h1>
         <h1>優惠管理</h1>
         <h1>優惠管理</h1>
         <h1>優惠管理</h1>
         <h1>優惠管理</h1>
         <h1>優惠管理</h1>
  </div>
</template>